### ISSUE TITLE
load_124 can probably load 125bp 

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Daniel-Liu-c0deb0t/simple-saca#1]
If you read 125bp, the 2 bits that 'point out' into the last byte always point to the same side since the basepairs are 2-bit aligned.
I would expect this to 'just work' without any modification, but didn't verify.

See also this comment: https://github.com/vigna/sux-rs/commit/69ed70fc25e588bfe0dc9c76864eea5433ec93f0#r129597950

**Comment by Daniel-Liu-c0deb0t** [comment]
Good observation! I've made the change to the code. Here are the possible cases for the least significant byte after shifting left to make sure the suffixes start on the most significant bit:
```
...1111 11111111
...1111 11111100
...1111 11110000
...1111 11000000
```
In all cases, there is 1bp (2 bits) extra leftover. So instead of masking out the entire least significant byte, it is sufficient to only mask out the last 3bp (6 bits) to get 125bp of context per AVX2 vector.
